{% set name = "loky" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/joblib/loky/archive/{{ version }}.tar.gz
  sha256: 0c230f3ca88c07ac270a67825982e5e153ab6ce910ba9f9d03253adf3a987722

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cloudpickle
    - psutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - loky

about:
  home: https://github.com/joblib/loky
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A robust implementation of concurrent.futures.ProcessPoolExecutor
  doc_url: https://loky.readthedocs.io/
  dev_url: https://github.com/joblib/loky

extra:
  recipe-maintainers:
    - jakirkham
    - tomMoral
    - ogrisel
    - pierreglaser
