{% set name = "loky" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ac7648a2c02758c37dcf3587ee4832d245ec5a4b0fec5cc0c6a9cc8e5695b53

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cloudpickle
    - psutil

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - loky

about:
  home: https://github.com/joblib/loky
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A robust implementation of concurrent.futures.ProcessPoolExecutor
  doc_url: https://loky.readthedocs.io/
  dev_url: https://github.com/joblib/loky

extra:
  recipe-maintainers:
    - jakirkham
    - tomMoral
    - ogrisel
    - pierreglaser
